apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fh5xu0pqk-python 
  janus-idp.io/tekton: fh5xu0pqk-python
  backstage.io/kubernetes-id: fh5xu0pqk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fh5xu0pqk-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml