apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fh5xu0pqk-python-gitops
  description: This is GitOps manifest for fh5xu0pqk-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=fh5xu0pqk-python
    backstage.io/kubernetes-id: fh5xu0pqk-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fh5xu0pqk-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fh5xu0pqk-python
