apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fh5xu0pqk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fh5xu0pqk-python 
  name: fh5xu0pqk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fh5xu0pqk-python 
